-- 코드를 작성해주세요

-- 암시적 조인
-- SELECT COUNT(*) AS "FISH_COUNT" 
-- FROM FISH_INFO AS FI, FISH_NAME_INFO AS FNI 
-- WHERE FI.FISH_TYPE = FNI.FISH_TYPE 
-- AND (FNI.FISH_NAME = "BASS" OR FNI.FISH_NAME = "SNAPPER");

-- 명시적 조인
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');
